<?php
define('orderbill_sales_bill_id','salesBillID');
define('orderbill_sales_bill_number','salesBillNumber');
define('orderbill_sales_bill_display_number','salesBillDisplayNumber');
define('orderbill_sales_bill_date','salesBillDate');
define('orderbill_customer_id','CustomerID');
define('orderbill_product_discount','ProductDiscount');
define('orderbill_total_discount','TotalDiscount');
define('orderbill_sales_tax','SalesTax');
define('orderbill_final_total','FinalTotal');
define('orderbill_cgst_rate','cgstRate');
define('orderbill_cgst_total','cgstTotal');
define('orderbill_sgst_rate','sgstRate');
define('orderbill_sgst_total','sgstTotal');
define('orderbill_igst_rate','igstRate');
define('orderbill_igst_total','igstTotal');
define('orderbill_cst_total','cstTotal');
define('orderbill_vat_total','vatTotal');
define('orderbill_total_qty','totalQty');
define('orderbill_chess_rate','chessRate');
define('orderbill_total_chess','totalChess');
define('orderbill_total_value','totalValue');
define('orderbill_total_taxable','totalTaxable');
define('orderbill_running_total','runningTotal');
define('orderbill_round_off','roundOff');
define('orderbill_sales_bill_total','salesBillTotal');
define('orderbill_company_ref_id','companyRefId');
define('orderbill_account_year_ref_id','accountYearRefId');
define('orderbill_fright','fright');
define('orderbill_created_by','createdBy');
define('orderbill_created_timetamp','createdTimeStamp');
define('orderbill_updated_by','updatedBy');
define('orderbill_updated_timeStamp','updatedTimeStamp');
define('orderbill_sales_bill_type','salesBillType');
define('orderbill_sales_bill_status','salesBillStatus');
define('orderbill_sales_bill_stage','salesBillStage');
define('orderbill_sales_bill_lock','salesBillLock');
define('orderbill_gst_type','salesBillGSTType');
define('orderbill_transport','transport');
define('orderbill_bundle','bundle');
define('orderbill_address_id','addressRefId');
define('orderbill_account_ref_id','accountRefId');
define('orderbill_vat_cst_flag','vatCstFlag');
define('orderbill_running_total_withtax','lineTotalwithtax');
define('orderbill_total_square_feet','totalSquareFeet');
define('orderbill_total_weight','totalWeight');
define('orderbill_total_currency','salesBillTotalConverCurrency');
define('orderbill_currency_value','salesBillTotalConverConversionValue');
define('orderbill_currency_ref_id','salesBillCurrencyRefId');
define('orderbill_despatched_to','despatchedTo');
define('orderbill_document_through','documentThrough');
define('orderbill_lorry_number','lorryNumber');
define('orderbill_packing_charge','packingCharge');
define('orderbill_postage_charge','postageCharge');
define('orderbill_purchaseOrderRefId','purchaseOrderRefId');
define('orderbill_ewayBillNumber','ewayBillNumber');
define('orderbill_totalNumberOfBags','totalNumberOfBags');
define('orderbill_salesBillDueDate','salesBillDueDate');
define('orderbill_creditPoint','creditPoint');
define('orderbill_customerType','customerType');
define('orderbill_creditPointFlag','creditPointFlag');
define('orderbill_incentiveAmount','incentiveAmount');
define('orderbill_advance_payment','advancePayment');
define('orderbill_deliveryDate','deliveryDate');
define('orderbill_balanceAmount','balanceAmount');
define('orderbill_orderStatus','orderStatus');
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates 
* and open the template in the editor.
 */

