<?php
define('purchaseorder_id','purchaseorderid');
define('purchaseorder_purchaseorderNumber','purchaseorderNumber');
define('purchaseorder_purchaseorderDisplayNumber','purchaseorderDisplayNumber');
define('purchaseorder_purchaseorderDate','purchaseorderDate');
define('purchaseorder_customer_id','CustomerID');
define('purchaseorder_product_discount','ProductDiscount');
define('purchaseorder_total_discount','TotalDiscount');
define('purchaseorder_sales_tax','SalesTax');
define('purchaseorder_final_total','FinalTotal');
define('purchaseorder_cgst_rate','cgstRate');
define('purchaseorder_cgst_total','cgstTotal');
define('purchaseorder_sgst_rate','sgstRate');
define('purchaseorder_sgst_total','sgstTotal');
define('purchaseorder_igst_rate','igstRate');
define('purchaseorder_igst_total','igstTotal');
define('purchaseorder_cst_total','cstTotal');
define('purchaseorder_vat_total','vatTotal');
define('purchaseorder_total_qty','totalQty');
define('purchaseorder_chess_rate','chessRate');
define('purchaseorder_total_chess','totalChess');
define('purchaseorder_total_value','totalValue');
define('purchaseorder_total_taxable','totalTaxable');
define('purchaseorder_running_total','runningTotal');
define('purchaseorder_round_off','roundOff');
define('purchaseorder_purchaseorderTotal','purchaseorderTotal');
define('purchaseorder_company_ref_id','companyRefId');
define('purchaseorder_account_year_ref_id','accountYearRefId');
define('purchaseorder_fright','fright');
define('purchaseorder_created_by','createdBy');
define('purchaseorder_created_timetamp','createdTimeStamp');
define('purchaseorder_updated_by','updatedBy');
define('purchaseorder_updated_timeStamp','updatedTimeStamp');
define('purchaseorder_purchaseorderType','purchaseorderType');
define('purchaseorder_purchaseorderStatus','purchaseorderStatus');
define('purchaseorder_purchaseorderStage','purchaseorderStage');
define('purchaseorder_purchaseorderLock','purchaseorderLock');
define('purchaseorder_purchaseorderGSTType','purchaseorderGSTType');
define('purchaseorder_transport','transport');
define('purchaseorder_bundle','bundle');
define('purchaseorder_address_id','addressRefId');
define('purchaseorder_account_ref_id','accountRefId');
define('purchaseorder_vat_cst_flag','vatCstFlag');
define('purchaseorder_running_total_withtax','lineTotalwithtax');
define('purchaseorder_total_square_feet','totalSquareFeet');
define('purchaseorder_total_weight','totalWeight');
define('purchaseorder_total_currency','salesBillTotalConverCurrency');
define('purchaseorder_currency_value','salesBillTotalConverConversionValue');
define('purchaseorder_currency_ref_id','salesBillCurrencyRefId');
define('purchaseorder_despatched_to','despatchedTo');
define('purchaseorder_document_through','documentThrough');
define('purchaseorder_lorry_number','lorryNumber');
define('purchaseorder_packing_charge','packingCharge');
define('purchaseorder_postage_charge','postageCharge');
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates 
* and open the template in the editor.
 */

