<?php
define('purchasepayment_id','purchasePaymentId');
define('purchasepayment_purchasebill_ref_id','purchaseBillRefId');
define('purchasepayment_date','paymentDate');
define('purchasepayment_mode','paymentMode');
define('purchasepayment_amount','paymentAmount');
define('purchasepayment_description','paymentDescription');
define('purchasepayment_customer_ref_id','customerRefId');
define('purchasepayment_company_ref_id','companyRefId');
define('purchasepayment_accountyear_ref_id','accountYearRefId');
define('purchasepayment_createdby','createdBy');
define('purchasepayment_updatedby','updatedBy');
define('purchasepayment_createdtimestamp','createdTimestamp');
define('purchasepayment_updatedtimestamp','updatedTimestamp');
define('purchasepayment_mode_description','modeDescription');
define('purchasepayment_account_ref_id','accountRefId');
define('purchasepayment_receipt_number','receiptNumber');
define('purchasepayment_bill_description','billDescription');