<?php
define('salesOrderItem_id','orderItemID');
define('salesOrderItem_sales_order_ref_id','orderRedfId');
define('salesOrderItem_item_name','itemName');
define('salesOrderItem_unit_rate','unitrate');
define('salesOrderItem_quantity','quantity');
define('salesOrderItem_linetotal','lineTotal');
define('salesOrderItem_cgst_rate','cgstRate');
define('salesOrderItem_cgst_total','cgstTotal');
define('salesOrderItem_sgst_rate','sgstRate');
define('salesOrderItem_sgst_total','sgstTotal');
define('salesOrderItem_igst_rate','igstRate');
define('salesOrderItem_igst_total','igstTotal');
define('salesOrderItem_UOM_ref_id','UOMRefId');
define('salesOrderItem_total_UOM_quantity','UOMQuantity');
define('salesOrderItem_customer_ref_id','orderCustomerRefId');
define('salesOrderItem_company_ref_id','companyRefId');
define('salesOrderItem_account_year_ref_id','accountYearRefId');
define('salesOrderItem_commodity_ref_id','commodityRefId');
