<?php
define('salesbill_sales_bill_id','salesBillID');
define('salesbill_sales_bill_number','salesBillNumber');
define('salesbill_sales_bill_display_number','salesBillDisplayNumber');
define('salesbill_sales_bill_date','salesBillDate');
define('salesbill_customer_id','CustomerID');
define('salesbill_product_discount','ProductDiscount');
define('salesbill_total_discount','TotalDiscount');
define('salesbill_sales_tax','SalesTax');
define('salesbill_final_total','FinalTotal');
define('salesbill_cgst_rate','cgstRate');
define('salesbill_cgst_total','cgstTotal');
define('salesbill_sgst_rate','sgstRate');
define('salesbill_sgst_total','sgstTotal');
define('salesbill_igst_rate','igstRate');
define('salesbill_igst_total','igstTotal');
define('salesbill_cst_total','cstTotal');
define('salesbill_vat_total','vatTotal');
define('salesbill_total_qty','totalQty');
define('salesbill_chess_rate','chessRate');
define('salesbill_total_chess','totalChess');
define('salesbill_total_value','totalValue');
define('salesbill_total_taxable','totalTaxable');
define('salesbill_running_total','runningTotal');
define('salesbill_round_off','roundOff');
define('salesbill_sales_bill_total','salesBillTotal');
define('salesbill_company_ref_id','companyRefId');
define('salesbill_account_year_ref_id','accountYearRefId');
define('salesbill_fright','fright');
define('salesbill_created_by','createdBy');
define('salesbill_created_timetamp','createdTimeStamp');
define('salesbill_updated_by','updatedBy');
define('salesbill_updated_timeStamp','updatedTimeStamp');
define('salesbill_sales_bill_type','salesBillType');
define('salesbill_sales_bill_status','salesBillStatus');
define('salesbill_sales_bill_stage','salesBillStage');
define('salesbill_sales_bill_lock','salesBillLock');
define('salesbill_gst_type','salesBillGSTType');
define('salesbill_transport','transport');
define('salesbill_bundle','bundle');
define('salesbill_address_id','addressRefId');
define('salesbill_account_ref_id','accountRefId');
define('salesbill_vat_cst_flag','vatCstFlag');
define('salesbill_running_total_withtax','lineTotalwithtax');
define('salesbill_total_square_feet','totalSquareFeet');
define('salesbill_total_weight','totalWeight');
define('salesbill_total_currency','salesBillTotalConverCurrency');
define('salesbill_currency_value','salesBillTotalConverConversionValue');
define('salesbill_currency_ref_id','salesBillCurrencyRefId');
define('salesbill_despatched_to','despatchedTo');
define('salesbill_document_through','documentThrough');
define('salesbill_lorry_number','lorryNumber');
define('salesbill_packing_charge','packingCharge');
define('salesbill_postage_charge','postageCharge');
define('salesbill_ewayBillNo','ewayBillNo');
define('salesbill_lrNumber','lrNumber');
define('salesbill_lrDate','lrDate');
define('salesbill_marksonpackage','marksonpackage');
define('salesbill_credit_note','creditNote');
define('salesbill_less','less');
define('salesbill_type','type');

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates 
* and open the template in the editor.
 */

