<?php
define('salesOrder_sales_order_id','salesOrderID');
define('salesOrder_sales_order_number','salesOrderNumber');
define('salesOrder_sales_order_date','salesOrderDate');
define('salesOrder_customer_id','customerID');
define('salesOrder_final_total','orderTotal');
define('salesOrder_cgst_total','orderCgst');
define('salesOrder_sgst_total','orderSgst');
define('salesOrder_igst_total','orderIgst');
define('salesOrder_total_qty','totalQuantity');
define('salesOrder_running_total','runningTotal');
define('salesOrder_round_off','roundOff');
define('salesOrder_company_ref_id','companyRefId');
define('salesOrder_account_year_ref_id','accountYearRefId');
define('salesOrder_created_by','createdBy');
define('salesOrder_created_timetamp','createdTimeStamp');
define('salesOrder_updated_by','updatedBy');
define('salesOrder_updated_timeStamp','updatedTimeStamp');
define('salesOrder_sales_order_status','salesOrderStatus');