<?php
define('salespayment_id','salesPaymentId');
define('salespayment_salesbill_ref_id','salesBillRefId');
define('salespayment_date','paymentDate');
define('salespayment_mode','paymentMode');
define('salespayment_amount','paymentAmount');
define('salespayment_description','paymentDescription');
define('salespayment_customer_ref_id','customerRefId');
define('salespayment_company_ref_id','companyRefId');
define('salespayment_accountyear_ref_id','accountYearRefId');
define('salespayment_createdby','createdBy');
define('salespayment_updatedby','updatedBy');
define('salespayment_createdtimestamp','createdTimestamp');
define('salespayment_updatedtimestamp','updatedTimestamp');
define('salespayment_mode_description','modeDescription');
define('salespayment_account_ref_id','accountRefId');
define('salespayment_receipt_number','receiptNumber');
define('salespayment_bill_description','billDescription');
define('salespayment_pendingAmount','pendingAmount');